"""Build a self-contained research report from verified result tables."""
import base64,html,json
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'results'
def main():
 e=json.loads((OUT/'expression_summary.json').read_text());f=json.loads((OUT/'followup_summary.json').read_text());v=json.loads((OUT/'validation_receipt.json').read_text())
 c=pd.read_csv(OUT/'frozen_candidates.csv');x=pd.read_csv(OUT/'external_expression_validation.csv');t=pd.read_csv(OUT/'TCGA_survival.csv');g=pd.read_csv(OUT/'GSE31210_survival.csv');paths=pd.read_csv(OUT/'pathway_enrichment.csv')
 assert e['pairs']==50 and f['tcga_complete_cases']==465 and f['geo_survival_eligible']==204
 assert v['identity_checks_passed'] and not f['statistical_survival_replications']
 comparison=c[['gene_name','log2FoldChange']].rename(columns={'gene_name':'Gene','log2FoldChange':'TCGA log2FC'}).merge(x[['gene','mean_log2_difference']],left_on='Gene',right_on='gene').drop(columns='gene').rename(columns={'mean_log2_difference':'GEO log2 difference'})
 comparison=comparison.merge(t[['gene','HR','q']],left_on='Gene',right_on='gene').drop(columns='gene').rename(columns={'HR':'TCGA HR','q':'TCGA survival q'})
 comparison=comparison.merge(g[['gene','HR','q']],left_on='Gene',right_on='gene').drop(columns='gene').rename(columns={'HR':'GEO HR','q':'GEO survival q'})
 comparison.to_csv(OUT/'candidate_comparison.csv',index=False)
 title='Lung adenocarcinoma: reproducible expression differences and survival follow-up'
 abstract=f'''A public-data reanalysis of TCGA-LUAD compared tumor and non-tumor tissue in {e['pairs']} matched patients. Of {e['genes_filtered_in']:,} expression-filtered genes, {e['significant_fdr05']:,} passed FDR <0.05 and convergence checks; {e['significant_fdr05_lfc1']:,} also had an absolute log2 fold change of at least 1. Ten expression-selected genes showed the same direction and passed ten-test FDR <0.05 in the independent GSE31210 microarray cohort. Age- and stage-adjusted overall-survival analyses included {f['tcga_complete_cases']} TCGA patients ({f['tcga_events']} deaths) and {f['geo_survival_eligible']} GEO patients ({f['geo_events']} deaths). No candidate passed survival FDR <0.05 in either cohort. These findings support reproducible tissue-expression differences, but do not establish prognostic biomarkers.'''
 sections=[]
 def section(name,body):sections.append(f'<section><h2>{html.escape(name)}</h2>{body}</section>')
 def fig(name,caption):
  data=base64.b64encode((OUT/'figures'/name).read_bytes()).decode();return f'<figure><img src="data:image/png;base64,{data}" alt="{html.escape(caption)}"><figcaption>{html.escape(caption)}</figcaption></figure>'
 section('What this project found',f'<p>{abstract}</p><div class="note"><strong>Interpretation:</strong> A gene can differ strongly between tumor and non-tumor tissue without reliably predicting which patients live longer. This study demonstrates that distinction. A nonsignificant survival result is not proof that an association is absent.</div>')
 section('Cohort and quality checks','''<p>The GDC inventory contained 601 files across 518 patients: 540 primary-tumor, 59 non-tumor, and 2 recurrent-tumor files. File counts were not treated as independent patients. The audit excluded all 35 files in ambiguous patient-condition groups, 12 further files with specified quality/treatment annotations, and the 2 recurrent tumors. Of 552 eligible files, 6 normal files lacked an eligible tumor pair. The final download comprised 496 unique primary tumors plus 50 paired normal samples.</p>
 <p>All 546 files passed their published MD5 checks. Gene IDs and annotation aligned exactly across samples; counts were nonnegative integers. All files stated GENCODE v36 and shared one GDC workflow version. Total gene-assigned reads ranged from 18.0 to 103.7 million per sample. No samples were removed after inspecting gene significance.</p>
 <p>The differential-expression design had 100 samples and 51 independent columns: patient effects plus tissue condition. Raw unstranded counts were used for inference. All paired samples had the same source-center code, but 11 pairs had different plate codes. A separate same-plate sensitivity analysis retained 39 pairs. Raw-read mapping quality and detailed sequencing batches were not independently reanalyzed.</p>'''+fig('01_pca.png','Figure 1. Tumor and non-tumor samples separate along PC1 (42.3% of variance). This descriptive plot uses the 1,000 most variable genes; separation is not a diagnostic-accuracy estimate.')+fig('04_library_sizes.png','Figure 2. Library sizes for the 100 matched samples. Color indicates tissue type; size-factor normalization accounts for library-scale differences in the model.'))
 section('Paired differential expression',f'''<p>PyDESeq2 0.5.4 fitted the model <code>~ patient + condition</code>, with tumor versus normal as the explicit contrast. Genes required at least 10 counts in at least 50 samples. Benjamini-Hochberg correction controlled the tested-gene false discovery rate. Sixty-one genes failed at least one convergence check and were excluded from supported significance and follow-up selection; original estimates and flags remain available.</p>
 <p>Among successfully fitted genes, {e['up']:,} were higher and {e['down']:,} lower in tumors at FDR &lt;0.05. The more descriptive threshold of FDR &lt;0.05 and |log2FC| &ge;1 retained {e['significant_fdr05_lfc1']:,} genes. Fold changes are unshrunk estimates. These are observational bulk-tissue differences and can reflect differences in cell composition or tumor purity.</p>'''+fig('02_volcano.png','Figure 3. Fold change and multiple-testing-adjusted significance for converged genes. The dashed line marks FDR 0.05; individual points do not establish clinical utility.')+fig('03_heatmap.png','Figure 4. Ten expression-selected genes, chosen before survival testing. Colors are within-gene z scores and do not compare absolute abundance between genes.'))
 section('Independent expression follow-up','''<p>The frozen candidate rule selected unique-symbol protein-coding genes with normalized mean &ge;100, FDR &lt;0.05 and |log2FC| &ge;1, ranked by absolute Wald statistic. The resulting list was PYCR1, SLC6A4, RTKN2, FABP4, SERTM1, FHL1, AGER, RGCC, KANK3, and RAMP2.</p>
 <p>GSE31210 included 226 primary lung adenocarcinomas and 20 normal tissues. Its MAS5-normalized array intensities were log2-transformed, uniquely annotated probes were mapped to genes, and multiple unambiguous probes were averaged on the log scale. All ten candidates agreed in direction with TCGA and passed ten-test BH FDR &lt;0.05 in exploratory Welch comparisons. PYCR1 was higher in tumors; the other nine were lower. Normal-to-tumor patient matching was not established in this cohort, so Welch independence is an assumption and external expression p-values should be interpreted cautiously.</p>
 <p>For all ten candidates, paired Wilcoxon sensitivity tests supported the same direction at ten-test FDR &lt;0.05 in both all 50 TCGA pairs and the 39 same-plate pairs. This supports robustness to that particular technical concern, without resolving all possible confounding.</p>'''+comparison.to_html(index=False,float_format=lambda a:f'{a:.3f}',border=0,classes='results-table')+'<p class="small">TCGA log2FC and GEO mean log2 intensity difference come from different assays and should not be treated as identically calibrated effect sizes. HR is per one within-cohort standard deviation of expression; q is the survival p-value after correction across all ten candidates.</p>')
 section('Survival: no corrected-significant candidate','''<p>Curated TCGA-CDR outcomes matched all 496 selected primary-tumor patients. Thirty-one patients were excluded from complete-case analysis: 13 lacked a usable positive survival time, 19 lacked age, and 8 lacked stage, with overlapping reasons. The retained 465 patients had 169 deaths and stages I/II/III/IV distributed as 251/114/76/24.</p>
 <p>The GEO cohort retained 204 patients after the submitter's 22 prognosis exclusions, with 30 deaths. Separate Cox models tested each candidate continuously, adjusted for age and categorical stage. TCGA used log2(TPM+1); GEO used log2 array intensity. Expression was standardized within each cohort. No survival-driven cutoff or multigene prediction score was optimized.</p>
 <p>No gene reached FDR &lt;0.05 in either cohort. AGER had nominal TCGA p=0.026 but q=0.240. FABP4 had nominal GEO p=0.0059 but q=0.0586. Neither is a corrected-significant replicated prognostic finding.</p>
 <p>Expression proportional-hazards checks did not reject after ten-test correction. Several TCGA stage terms showed nominal proportional-hazards concerns; a stage-stratified sensitivity model again found no gene at FDR &lt;0.05. Seven GEO candidates showed quadratic-shape diagnostic signals after correction: PYCR1, SLC6A4, SERTM1, FHL1, RGCC, KANK3, and RAMP2. With only 30 GEO deaths, these post-fit diagnostics highlight uncertainty in simple linear hazard assumptions; they are not validated nonlinear biomarker discoveries. Excluding annotation-positive TCGA cases retained 407 patients and 144 deaths, with no corrected-significant candidate.</p>'''+fig('05_survival_forest.png','Figure 5. Age- and stage-adjusted survival HRs and nominal 95% confidence intervals. Confidence intervals are not multiplicity-adjusted; no candidate passed ten-test FDR 0.05.')+fig('06_KM_TCGA.png','Figure 6. Descriptive TCGA survival curves for PYCR1, the first expression-ranked candidate. Cohort-median groups were not optimized; curves are unadjusted and do not replace the continuous Cox analysis.')+fig('06_KM_GSE31210.png','Figure 7. Independent descriptive PYCR1 survival curves with at-risk counts. Wide late follow-up intervals reflect small numbers remaining under observation.'))
 section('Pathway context',f'''<p>Preranked enrichment used converged-gene Wald statistics, 50 Hallmark 2020 gene sets, 1,000 permutations, and seed 20261005. Duplicate symbols were resolved using highest normalized mean expression, independently of significance. {f['hallmark_fdr05']} gene sets had enrichment FDR &lt;0.05. Positive enrichment included E2F targets, G2-M checkpoint, MYC targets, glycolysis, and DNA repair. Negative enrichment included myogenesis and TNF-alpha signaling via NF-kB.</p>
 <p>These patterns are consistent with differences in proliferative, metabolic, and tissue-composition programs; the analysis cannot distinguish cellular composition from within-cell regulation or establish causal pathway activation. Zero values in permutation-estimated FDR output mean none observed in the sampled null tail, not a true probability of zero. Gene-set permutation inference does not fully account for intergene correlation.</p>'''+fig('07_pathways.png','Figure 8. Twelve pathways with the lowest estimated enrichment FDR. Positive scores indicate concentration near the tumor-upregulated end of the gene ranking.'))
 section('Limitations and supportable claims','''<ul><li>This is an AI-assisted public-data reanalysis, not a prospective clinical study or a claim of novel biomarker discovery.</li><li>TCGA non-tumor tissue is not healthy-volunteer tissue. Tumor purity, immune/stromal composition, treatment, smoking, and residual technical effects can influence expression and prognosis.</li><li>Excluding ambiguous samples improves identity certainty but can introduce selection bias. Complete-case survival analysis can also be biased by missingness.</li><li>GEO was stage I-II, used a different assay, and had only 30 eligible deaths. TCGA outcomes use a historical 2018 freeze. Cohort endpoint origins and follow-up contexts are not identical.</li><li>Seven GEO genes had nonlinearity diagnostic signals; the linear-HR summaries are limited. No clinical risk score, predictive accuracy, or treatment decision rule was validated.</li><li>Independent tissue-expression concordance supports reproducibility of direction. It does not by itself support prognosis, causality, novelty, or clinical usefulness.</li></ul>
 <p><strong>Supportable conclusion:</strong> A reproducible, patient-aware analysis found tumor-associated expression differences and external directional agreement for ten candidates, while corrected survival testing did not establish prognostic associations under the specified models.</p>''')
 section('Reproducibility and sources','''<p>The project contains source scripts, frozen dependencies, raw-count matrices for the paired cohort, complete gene results, sample exclusions, candidate expression values, clinical eligibility tables, model diagnostics, and reference checksums. Large downloaded inputs remain in the local work folder and can be retrieved again with the included scripts. The package contains no private credentials.</p>
 <ol><li><a href="https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/">NCI GDC mRNA pipeline and gene counts</a></li><li><a href="https://gdc.cancer.gov/about-data/publications/PanCan-Clinical-2018">Liu et al., TCGA Pan-Cancer Clinical Data Resource (Cell, 2018)</a></li><li><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE31210">GEO GSE31210 and its original publications</a></li><li><a href="https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GPL570">GPL570 probe annotation</a></li><li><a href="https://pydeseq2.readthedocs.io/">PyDESeq2</a>, <a href="https://lifelines.readthedocs.io/">lifelines</a>, and <a href="https://gseapy.readthedocs.io/">GSEApy</a></li></ol>
 <p>Prepared for Hamza Ahmed. Data retrieved and analysis completed October 5, 2026 (America/Chicago). Code and draft interpretation were generated and executed with AI assistance. Review the methods and practice explaining them before using this project in an application or interview.</p>''')
 style='''body{margin:0;background:#f1f4f6;color:#203040;font:17px/1.65 system-ui,Arial,sans-serif}header{background:#102d3b;color:white;padding:58px max(24px,calc((100% - 1060px)/2))}header h1{font-size:clamp(30px,4vw,46px);line-height:1.15;max-width:1000px;margin:14px 0}header p{color:#b7d9de}.eyebrow{letter-spacing:2px;font-size:12px;text-transform:uppercase}main{max-width:1060px;margin:auto;padding:26px 20px 60px}section{background:white;border:1px solid #dce4e8;border-radius:12px;margin:20px 0;padding:30px}h2{font-size:26px;line-height:1.25;color:#124f61;margin-top:0}figure{margin:26px 0}img{max-width:100%;height:auto}figcaption,.small{font-size:14px;color:#586b77}.note{border-left:4px solid #158a8a;padding:18px;background:#edf7f6}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric{background:#e8f3f3;padding:20px;border-radius:9px}.metric b{display:block;font-size:30px;color:#12545c}.metric span{font-size:13px}.results-table{width:100%;font-size:13px;border-collapse:collapse}.results-table th,.results-table td{padding:9px 6px;border-bottom:1px solid #dde5e9;text-align:right}.results-table th:first-child,.results-table td:first-child{text-align:left}a{color:#096d86}code{background:#edf0f3;padding:2px 5px}li{margin:10px 0}@media(max-width:650px){section{padding:18px;overflow-x:auto}.metrics{grid-template-columns:repeat(2,1fr)}}@media print{body{background:white}header{padding:25px;background:white;color:#123}header p{color:#456}main{padding:0}section{border:0;padding:15px 0;break-inside:auto}figure{break-inside:avoid}.metrics{break-inside:avoid}}'''
 metrics=f'<div class="metrics"><div class="metric"><b>50</b><span>matched TCGA pairs</span></div><div class="metric"><b>19,026</b><span>expression-filtered genes</span></div><div class="metric"><b>10 / 10</b><span>external expression directions agree</span></div><div class="metric"><b>0 / 10</b><span>corrected-significant survival candidates</span></div></div>'
 page=f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)}</title><style>{style}</style></head><body><header><div class="eyebrow">Research portfolio · TCGA-LUAD + GSE31210</div><h1>{title}</h1><p>Completed analysis · October 5, 2026 · Prepared for Hamza Ahmed</p></header><main>{metrics}{"".join(sections)}</main></body></html>'
 (ROOT/'Research_Report.html').write_text(page,encoding='utf-8')
 summary=f'''# {title}\n\n{abstract}\n\n## Main findings\n\n- {e['significant_fdr05']:,} genes passed FDR <0.05 and convergence checks; {e['significant_fdr05_lfc1']:,} also met |log2FC| >=1.\n- All ten frozen expression candidates agreed in direction in GSE31210 and passed exploratory external expression FDR <0.05.\n- All ten passed paired sensitivity tests in both 50 total pairs and 39 same-plate pairs.\n- No corrected-significant survival association was established in TCGA or GEO.\n- {f['hallmark_fdr05']} of 50 Hallmark sets had enrichment FDR <0.05.\n\n## Interpretation\n\nThe project supports reproducible tissue-expression differences. It does not establish prognostic biomarkers, causality, clinical utility, or novel discoveries. External expression matching is unresolved, survival diagnostics identify limitations, and the GEO survival cohort has only 30 deaths. See Research_Report.html for complete methods, plots, diagnostics, and limitations.\n\n## Artifact map\n\n- Results: results/ contains the full differential-expression table, paired raw matrix, frozen candidates, survival results, and pathway results.\n- QC and visuals: results/figures/ contains PNG and SVG charts; sample_qc.csv and validation_receipt.json record checks.\n- Provenance: metadata/, requirements-lock.txt, docs/analysis_plan_v2.md, and docs/decision_log.md preserve selection and implementation details.\n- Interpretation: this summary, Research_Report.html, and docs/learning_guide.md explain supported findings and claim boundaries.\n\nAI-assisted code and analysis prepared for Hamza Ahmed; review and understanding are needed before independent presentation.\n'''
 (ROOT/'Research_Summary.md').write_text(summary,encoding='utf-8')
 print('Created self-contained research report and summary.')
if __name__=='__main__':main()
